package com.mihani.entities;

public enum Cities {

    TAROUDANT, AGADIR, MARRAKECH, CASABLANCA, RABAT, TANGER, FES, MEKNES, OUJDA, BERKANE, NADOR, TETOUAN, KENITRA, EL_JADIDA, SAFI, ESSAOUIRA, EL_HOCEIMA, LAAYOUNE, DAKHLA, AUTRE;

}
