package com.mihani.entities;

public enum Cities {

    TAROUDANT, AGADIR, MARRAKECH, CASABLANCA, RABAT, TANGER, FES, MEKNES, OUJDA, BERKANE, NADOR, TETOUAN, KENITRA, SAFI, ESSAOUIRA, LAAYOUNE, DAKHLA, AUTRE;

}
